### ISSUE TITLE
Bug in condition_variable_any2

### ISSUE THREAD

**Issue by HowardHinnant** [josuttis/jthread#1]
There's a bug in condition_variable_any2 that I don't _think_ impacts the implementation of jthread.  However this is such a complex subject that no stone should be left unturned.

> `~condition_variable_any();`
> 
> _Requires_: There shall be no thread blocked on *this. [Note: That is, all threads shall have been notified; they may subsequently block on the lock specified in the wait. This relaxes the usual rules, which would have required all wait calls to happen before destruction. Only the notification to unblock the wait needs to happen before destruction. The user should take care to ensure that no threads wait on *this once the destructor has been started, especially when the waiting threads are calling the wait functions in a loop or using the overloads of wait, wait_for, or wait_until that take a predicate.
> —end note]

That big long note means `~condition_variable_any()` can execute _before_ a signaled thread returns from a wait.  If this happens with `condition_variable_any2`, that waiting thread will attempt to lock the destructed mutex `mut`.  To fix this, there must be shared ownership of the data member `mut` between the `condition_variable_any` object and the member functions `wait` (`wait_for`, etc.).

libc++'s implementation gets this right:  https://github.com/llvm-mirror/libcxx/blob/master/include/condition_variable

It holds the data member `mutex` with a `shared_ptr<mutex>` instead of `mutex` directly, and the wait functions create a local `shared_ptr<mutex>` copy on entry so that if `*this` destructs out from under the thread executing the `wait` function, the mutex stays alive until the `wait` function returns.

**Comment by josuttis** [comment]
Thus bug was fixed by  6900b011a54a84c4e2931dd730dda34a2dd9e103
on 2018-11-08.
