### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dacap** [josuttis/jthread#17]
Hi there, just as a clarification, I think the license of the project should point to https://creativecommons.org/licenses/by/4.0/ if the project is really licensed under the Creative Commons Attribution 4.0 International License (similar to MIT).

At the moment the README is pointing to https://creativecommons.org/licenses/by-sa/4.0/ which is CC Attribution-ShareAlike 4.0 International (similar to GPL).

**Comment by josuttis** [comment]
fixed as requested.
Thanks
