### ISSUE TITLE
Algorithms with stop_token?

### ISSUE THREAD

**Issue by tomeksowi** [josuttis/jthread#18]
First off, `jthreads` are a very interesting proposal for the std lib, I hope you drive it home. Thanks for your work.

Having a means of collaboratively requesting a halt of a chunk of work doesn't end with `jthreads`. It would be immensely useful to be able to pass the `stop_token` to other parts of the library, particularily std algorithm. Currently the way to stop e.g. `std::sort` on a large array is to pass it a predicate that throws an exception when stop is requested. This approach has issues of its own: exception safety, the need to wrap all `sort` calls with such predicates in `try` blocks, not usable in codebases with disabled exceptions, etc. Not to mention treating a perfectly normal case in GUI programming (user clicked away and wants to see another item list) as exceptional is somewhat hackish.

Are there any plans to respect the `stop_token` in other parts of the standard library?

**Comment by lewissbaker** [comment]
Yes, I can see the `stop_token` being useful in many other places within the standard library over time.

The initial focus, which would need to be for C++23 as it's too late in the C++20 timeframe to consider adding additional `stop_token` support, is going to be to add cancellation/stop support to the async operations introduced with executors and hopefully networking. However, I anticipate these might also include the async versions of parallel algorithms and could therefore eventually also apply to the normal synchronous std algorithms.

Integration of `stop_token` into other parts of the std library has not yet been proposed.

**Comment by tomeksowi** [comment]
Alright, closing as out of scope for this proposal.
