### ISSUE TITLE
stop_token/stop_source method bikeshedding

### ISSUE THREAD

**Issue by lewissbaker** [josuttis/jthread#6]
LEWG suggested using the "request" and "requested" terminology to indicate that the operation is an asynchronous request to stop and that the operation is not stopped immediately.

Also, I think the name change from `interrupt` to `stop` is an improvement.

This then raises the question about what to name the methods.

Some possibilities to consider:
* `stop_source`
  * `signal_stop()`  => `request_stop()`
  * `valid()` => `stop_requestable()` or `stoppable()` or `can_be_stopped()` (or just leave as `valid()`)
  * `stop_signalled()` => `stop_requested()`
* `stop_token`
  * `stop_signalled()` => `stop_requested()`
  * `stop_done_or_possible()` => `stop_requestable()` or `stoppable()` or `can_be_stopped()` or `can_stop_be_requested()`

**Comment by josuttis** [comment]
Current wording used:
 request_stop()
 stop_requested()
 stoppable()
 callbacks_ignored()

**Comment by lewissbaker** [comment]
Also see this comment for a use-case: https://github.com/josuttis/jthread/commit/89530e726690dc92a0f4761fdf943d6958d3b8a9#r31923584

I think that the `callbacks_ignored()` naming is a bit too specific to callbacks. It can be used in cases where the function is polling for `stop_requested()` and does not use callbacks so I think it needs to be named something a bit more generic. The general question we are asking is "can the `stop_requested()` method ever return `true`"?

I think `stoppable()` is an improvement but I think that the term "stoppable" also feels like it applies more to the operation that accepts a `std::stop_token` than to the stop-token itself. e.g. It makes sense to say that a function that accepts a `stop_token` represents a "stoppable" operation, but it doesn't seem to make as much sense to say that the `stop_token` is "stoppable".

For this reason I'm leaning slightly towards either `stop_requestable()` or `can_stop_be_requested()`, but I'm not 100% happy with these options either.

**Comment by kirkshoop** [comment]
how about removing some complexity in the meaning of the methods. We could add a `final()`method to `stop_token` that is true when the state cannot be changed. when `final()` returns true `stop_requested()` need only be called once to detect the final state.

```cpp
float calculate_avg(std::span<float> values, stop_token st = {})
{
  float sum = 0.0f;
  if (!st.final()) // or st.frozen()
  {
```

I would also prefer the stop_source be contextually convertible to bool rather than have a bool method named valid/stoppable/etc.. Now that there are two objects source & token, the meaning should not be ambiguous anymore.

The result of these changes would be:

- `stop_source`
  - `signal_stop()` => `request_stop()`
  - `valid()` => `operator bool()`
  - `stop_signalled()` => `stop_requested()`
- `stop_token`
  - `stop_signalled()` => `stop_requested()`
  - `stop_done_or_possible()` - removed
  - `final()` - added

**Comment by lewissbaker** [comment]
After discussion with @josuttis we decided that the naming that will appear in R8 of the paper is:
* `stop_source`
  * `request_stop()`
  * `stop_requested()`
  * `stop_possible()`
* `stop_token`
  * `stop_requested()`
  * `stop_possible()`

**Comment by kirkshoop** [comment]
Why does stop_source have stop_possible? As long as a source exists it is possible.

**Comment by josuttis** [comment]
no, not if it doesn't have an associated sharedstop state
(created with nostopstate or moved away ) 

Am 17. Januar 2019 21:07:10 MEZ schrieb Kirk Shoop <notifications@github.com>:
>Why does stop_source have stop_possible? As long as a source exists it
>is possible. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/josuttis/jthread/issues/6#issuecomment-455313985

--- 
Diese Nachricht wurde von meinem Fairphone2 mit K-9 Mail gesendet.

**Comment by lewissbaker** [comment]
LEWG accepted the proposed naming of `stop_token`, `stop_source`, `stop_callback` types and `stop_possible()`, `stop_requested()` and `request_stop()` method names.

Closing.
